python -u  ./folder_aws/transformers/examples/research_projects/mlm_wwm/run_mlm_wwm.py \
    --model_name_or_path roberta-base \
    --train_file ./textos_train.csv \
    --validation_file ./textos_val.csv  \
    --output_dir ./roberta_zara_27003 \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --evaluation_strategy steps \
    --per_device_train_batch_size 8  \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 16  \
    --learning_rate 5e-5  \
    --save_steps 250  \
    --logging_steps 250 \
    --overwrite_cache \
    --max_seq_length 512 \
    --eval_accumulation_steps 10 \
    --load_best_model_at_end \
    --run_name roberta_2703 \
    --save_total_limit 10  \
    --adam_beta2 0.98 --adam_epsilon 1e-6 --weight_decay 0.01 --num_train_epochs 5
